// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `vc.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:UnsignedVerifiableCredential)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UnsignedVerifiableCredential {
    // message fields
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.context)
    pub context: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.id)
    pub id: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.credential_type)
    pub credential_type: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.name)
    pub name: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.description)
    pub description: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.issuer)
    pub issuer: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.credential_subject)
    pub credential_subject: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.valid_from)
    pub valid_from: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.valid_until)
    pub valid_until: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.credential_status)
    pub credential_status: ::protobuf::MessageField<Status>,
    // @@protoc_insertion_point(field:UnsignedVerifiableCredential.credential_schema)
    pub credential_schema: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // special fields
    // @@protoc_insertion_point(special_field:UnsignedVerifiableCredential.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UnsignedVerifiableCredential {
    fn default() -> &'a UnsignedVerifiableCredential {
        <UnsignedVerifiableCredential as ::protobuf::Message>::default_instance()
    }
}

impl UnsignedVerifiableCredential {
    pub fn new() -> UnsignedVerifiableCredential {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(11);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "context",
            |m: &UnsignedVerifiableCredential| { &m.context },
            |m: &mut UnsignedVerifiableCredential| { &mut m.context },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "id",
            |m: &UnsignedVerifiableCredential| { &m.id },
            |m: &mut UnsignedVerifiableCredential| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "credential_type",
            |m: &UnsignedVerifiableCredential| { &m.credential_type },
            |m: &mut UnsignedVerifiableCredential| { &mut m.credential_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "name",
            |m: &UnsignedVerifiableCredential| { &m.name },
            |m: &mut UnsignedVerifiableCredential| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "description",
            |m: &UnsignedVerifiableCredential| { &m.description },
            |m: &mut UnsignedVerifiableCredential| { &mut m.description },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "issuer",
            |m: &UnsignedVerifiableCredential| { &m.issuer },
            |m: &mut UnsignedVerifiableCredential| { &mut m.issuer },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "credential_subject",
            |m: &UnsignedVerifiableCredential| { &m.credential_subject },
            |m: &mut UnsignedVerifiableCredential| { &mut m.credential_subject },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "valid_from",
            |m: &UnsignedVerifiableCredential| { &m.valid_from },
            |m: &mut UnsignedVerifiableCredential| { &mut m.valid_from },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "valid_until",
            |m: &UnsignedVerifiableCredential| { &m.valid_until },
            |m: &mut UnsignedVerifiableCredential| { &mut m.valid_until },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Status>(
            "credential_status",
            |m: &UnsignedVerifiableCredential| { &m.credential_status },
            |m: &mut UnsignedVerifiableCredential| { &mut m.credential_status },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "credential_schema",
            |m: &UnsignedVerifiableCredential| { &m.credential_schema },
            |m: &mut UnsignedVerifiableCredential| { &mut m.credential_schema },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UnsignedVerifiableCredential>(
            "UnsignedVerifiableCredential",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UnsignedVerifiableCredential {
    const NAME: &'static str = "UnsignedVerifiableCredential";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.context.push(is.read_string()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.id)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_type)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.name)?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.description)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.issuer)?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_subject)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.valid_from)?;
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.valid_until)?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_status)?;
                },
                90 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_schema)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.context {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_type.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.name.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.description.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.issuer.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_subject.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.valid_from.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.valid_until.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_status.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_schema.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.context {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.credential_type.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.name.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.description.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.issuer.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.credential_subject.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.valid_from.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if let Some(v) = self.valid_until.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        if let Some(v) = self.credential_status.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if let Some(v) = self.credential_schema.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UnsignedVerifiableCredential {
        UnsignedVerifiableCredential::new()
    }

    fn clear(&mut self) {
        self.context.clear();
        self.id.clear();
        self.credential_type.clear();
        self.name.clear();
        self.description.clear();
        self.issuer.clear();
        self.credential_subject.clear();
        self.valid_from.clear();
        self.valid_until.clear();
        self.credential_status.clear();
        self.credential_schema.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UnsignedVerifiableCredential {
        static instance: UnsignedVerifiableCredential = UnsignedVerifiableCredential {
            context: ::std::vec::Vec::new(),
            id: ::protobuf::MessageField::none(),
            credential_type: ::protobuf::MessageField::none(),
            name: ::protobuf::MessageField::none(),
            description: ::protobuf::MessageField::none(),
            issuer: ::protobuf::MessageField::none(),
            credential_subject: ::protobuf::MessageField::none(),
            valid_from: ::protobuf::MessageField::none(),
            valid_until: ::protobuf::MessageField::none(),
            credential_status: ::protobuf::MessageField::none(),
            credential_schema: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UnsignedVerifiableCredential {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UnsignedVerifiableCredential").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UnsignedVerifiableCredential {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UnsignedVerifiableCredential {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:VerifiableCredential)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VerifiableCredential {
    // message fields
    // @@protoc_insertion_point(field:VerifiableCredential.context)
    pub context: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:VerifiableCredential.id)
    pub id: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:VerifiableCredential.credential_type)
    pub credential_type: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiableCredential.name)
    pub name: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiableCredential.description)
    pub description: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiableCredential.issuer)
    pub issuer: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiableCredential.credential_subject)
    pub credential_subject: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiableCredential.valid_from)
    pub valid_from: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:VerifiableCredential.valid_until)
    pub valid_until: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:VerifiableCredential.credential_status)
    pub credential_status: ::protobuf::MessageField<Status>,
    // @@protoc_insertion_point(field:VerifiableCredential.credential_schema)
    pub credential_schema: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiableCredential.proof)
    pub proof: ::protobuf::MessageField<Proof>,
    // special fields
    // @@protoc_insertion_point(special_field:VerifiableCredential.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VerifiableCredential {
    fn default() -> &'a VerifiableCredential {
        <VerifiableCredential as ::protobuf::Message>::default_instance()
    }
}

impl VerifiableCredential {
    pub fn new() -> VerifiableCredential {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(12);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "context",
            |m: &VerifiableCredential| { &m.context },
            |m: &mut VerifiableCredential| { &mut m.context },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "id",
            |m: &VerifiableCredential| { &m.id },
            |m: &mut VerifiableCredential| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "credential_type",
            |m: &VerifiableCredential| { &m.credential_type },
            |m: &mut VerifiableCredential| { &mut m.credential_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "name",
            |m: &VerifiableCredential| { &m.name },
            |m: &mut VerifiableCredential| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "description",
            |m: &VerifiableCredential| { &m.description },
            |m: &mut VerifiableCredential| { &mut m.description },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "issuer",
            |m: &VerifiableCredential| { &m.issuer },
            |m: &mut VerifiableCredential| { &mut m.issuer },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "credential_subject",
            |m: &VerifiableCredential| { &m.credential_subject },
            |m: &mut VerifiableCredential| { &mut m.credential_subject },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "valid_from",
            |m: &VerifiableCredential| { &m.valid_from },
            |m: &mut VerifiableCredential| { &mut m.valid_from },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "valid_until",
            |m: &VerifiableCredential| { &m.valid_until },
            |m: &mut VerifiableCredential| { &mut m.valid_until },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Status>(
            "credential_status",
            |m: &VerifiableCredential| { &m.credential_status },
            |m: &mut VerifiableCredential| { &mut m.credential_status },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "credential_schema",
            |m: &VerifiableCredential| { &m.credential_schema },
            |m: &mut VerifiableCredential| { &mut m.credential_schema },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Proof>(
            "proof",
            |m: &VerifiableCredential| { &m.proof },
            |m: &mut VerifiableCredential| { &mut m.proof },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VerifiableCredential>(
            "VerifiableCredential",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VerifiableCredential {
    const NAME: &'static str = "VerifiableCredential";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.context.push(is.read_string()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.id)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_type)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.name)?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.description)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.issuer)?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_subject)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.valid_from)?;
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.valid_until)?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_status)?;
                },
                90 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.credential_schema)?;
                },
                98 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.proof)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.context {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_type.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.name.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.description.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.issuer.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_subject.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.valid_from.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.valid_until.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_status.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.credential_schema.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.proof.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.context {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.credential_type.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.name.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.description.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.issuer.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.credential_subject.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.valid_from.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if let Some(v) = self.valid_until.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        if let Some(v) = self.credential_status.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        if let Some(v) = self.credential_schema.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        }
        if let Some(v) = self.proof.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(12, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VerifiableCredential {
        VerifiableCredential::new()
    }

    fn clear(&mut self) {
        self.context.clear();
        self.id.clear();
        self.credential_type.clear();
        self.name.clear();
        self.description.clear();
        self.issuer.clear();
        self.credential_subject.clear();
        self.valid_from.clear();
        self.valid_until.clear();
        self.credential_status.clear();
        self.credential_schema.clear();
        self.proof.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VerifiableCredential {
        static instance: VerifiableCredential = VerifiableCredential {
            context: ::std::vec::Vec::new(),
            id: ::protobuf::MessageField::none(),
            credential_type: ::protobuf::MessageField::none(),
            name: ::protobuf::MessageField::none(),
            description: ::protobuf::MessageField::none(),
            issuer: ::protobuf::MessageField::none(),
            credential_subject: ::protobuf::MessageField::none(),
            valid_from: ::protobuf::MessageField::none(),
            valid_until: ::protobuf::MessageField::none(),
            credential_status: ::protobuf::MessageField::none(),
            credential_schema: ::protobuf::MessageField::none(),
            proof: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VerifiableCredential {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VerifiableCredential").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VerifiableCredential {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifiableCredential {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:VerifiablePresentation)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VerifiablePresentation {
    // message fields
    // @@protoc_insertion_point(field:VerifiablePresentation.context)
    pub context: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:VerifiablePresentation.id)
    pub id: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:VerifiablePresentation.presentation_type)
    pub presentation_type: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiablePresentation.verifiable_credential)
    pub verifiable_credential: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:VerifiablePresentation.holder)
    pub holder: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // special fields
    // @@protoc_insertion_point(special_field:VerifiablePresentation.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VerifiablePresentation {
    fn default() -> &'a VerifiablePresentation {
        <VerifiablePresentation as ::protobuf::Message>::default_instance()
    }
}

impl VerifiablePresentation {
    pub fn new() -> VerifiablePresentation {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "context",
            |m: &VerifiablePresentation| { &m.context },
            |m: &mut VerifiablePresentation| { &mut m.context },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "id",
            |m: &VerifiablePresentation| { &m.id },
            |m: &mut VerifiablePresentation| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "presentation_type",
            |m: &VerifiablePresentation| { &m.presentation_type },
            |m: &mut VerifiablePresentation| { &mut m.presentation_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "verifiable_credential",
            |m: &VerifiablePresentation| { &m.verifiable_credential },
            |m: &mut VerifiablePresentation| { &mut m.verifiable_credential },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "holder",
            |m: &VerifiablePresentation| { &m.holder },
            |m: &mut VerifiablePresentation| { &mut m.holder },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VerifiablePresentation>(
            "VerifiablePresentation",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VerifiablePresentation {
    const NAME: &'static str = "VerifiablePresentation";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.context.push(is.read_string()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.id)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.presentation_type)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.verifiable_credential)?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.holder)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.context {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.presentation_type.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.verifiable_credential.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.holder.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.context {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.presentation_type.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.verifiable_credential.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.holder.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VerifiablePresentation {
        VerifiablePresentation::new()
    }

    fn clear(&mut self) {
        self.context.clear();
        self.id.clear();
        self.presentation_type.clear();
        self.verifiable_credential.clear();
        self.holder.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VerifiablePresentation {
        static instance: VerifiablePresentation = VerifiablePresentation {
            context: ::std::vec::Vec::new(),
            id: ::protobuf::MessageField::none(),
            presentation_type: ::protobuf::MessageField::none(),
            verifiable_credential: ::protobuf::MessageField::none(),
            holder: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VerifiablePresentation {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VerifiablePresentation").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VerifiablePresentation {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifiablePresentation {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Status)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Status {
    // message fields
    // @@protoc_insertion_point(field:Status.id)
    pub id: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:Status.status_type)
    pub status_type: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // special fields
    // @@protoc_insertion_point(special_field:Status.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Status {
    fn default() -> &'a Status {
        <Status as ::protobuf::Message>::default_instance()
    }
}

impl Status {
    pub fn new() -> Status {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "id",
            |m: &Status| { &m.id },
            |m: &mut Status| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "status_type",
            |m: &Status| { &m.status_type },
            |m: &mut Status| { &mut m.status_type },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Status>(
            "Status",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Status {
    const NAME: &'static str = "Status";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.id)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.status_type)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.status_type.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.status_type.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Status {
        Status::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.status_type.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Status {
        static instance: Status = Status {
            id: ::protobuf::MessageField::none(),
            status_type: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Status {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Status").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Status {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Status {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CredentialSchema)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CredentialSchema {
    // message fields
    // @@protoc_insertion_point(field:CredentialSchema.id)
    pub id: ::std::string::String,
    // @@protoc_insertion_point(field:CredentialSchema.schema_type)
    pub schema_type: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:CredentialSchema.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CredentialSchema {
    fn default() -> &'a CredentialSchema {
        <CredentialSchema as ::protobuf::Message>::default_instance()
    }
}

impl CredentialSchema {
    pub fn new() -> CredentialSchema {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &CredentialSchema| { &m.id },
            |m: &mut CredentialSchema| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "schema_type",
            |m: &CredentialSchema| { &m.schema_type },
            |m: &mut CredentialSchema| { &mut m.schema_type },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CredentialSchema>(
            "CredentialSchema",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CredentialSchema {
    const NAME: &'static str = "CredentialSchema";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.id = is.read_string()?;
                },
                18 => {
                    self.schema_type = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if !self.schema_type.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.schema_type);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if !self.schema_type.is_empty() {
            os.write_string(2, &self.schema_type)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CredentialSchema {
        CredentialSchema::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.schema_type.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CredentialSchema {
        static instance: CredentialSchema = CredentialSchema {
            id: ::std::string::String::new(),
            schema_type: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CredentialSchema {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CredentialSchema").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CredentialSchema {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CredentialSchema {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:Proof)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Proof {
    // message fields
    // @@protoc_insertion_point(field:Proof.id)
    pub id: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:Proof.proof_type)
    pub proof_type: ::std::string::String,
    // @@protoc_insertion_point(field:Proof.proof_purpose)
    pub proof_purpose: ::std::string::String,
    // @@protoc_insertion_point(field:Proof.verification_method)
    pub verification_method: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:Proof.cryptosuite)
    pub cryptosuite: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:Proof.created)
    pub created: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:Proof.expires)
    pub expires: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:Proof.domain)
    pub domain: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // @@protoc_insertion_point(field:Proof.challenge)
    pub challenge: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:Proof.proof_value)
    pub proof_value: ::std::string::String,
    // @@protoc_insertion_point(field:Proof.previous_proof)
    pub previous_proof: ::protobuf::MessageField<::protobuf::well_known_types::wrappers::StringValue>,
    // @@protoc_insertion_point(field:Proof.nonce)
    pub nonce: ::protobuf::MessageField<::protobuf::well_known_types::struct_::Value>,
    // special fields
    // @@protoc_insertion_point(special_field:Proof.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Proof {
    fn default() -> &'a Proof {
        <Proof as ::protobuf::Message>::default_instance()
    }
}

impl Proof {
    pub fn new() -> Proof {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(12);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "id",
            |m: &Proof| { &m.id },
            |m: &mut Proof| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "proof_type",
            |m: &Proof| { &m.proof_type },
            |m: &mut Proof| { &mut m.proof_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "proof_purpose",
            |m: &Proof| { &m.proof_purpose },
            |m: &mut Proof| { &mut m.proof_purpose },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "verification_method",
            |m: &Proof| { &m.verification_method },
            |m: &mut Proof| { &mut m.verification_method },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "cryptosuite",
            |m: &Proof| { &m.cryptosuite },
            |m: &mut Proof| { &mut m.cryptosuite },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "created",
            |m: &Proof| { &m.created },
            |m: &mut Proof| { &mut m.created },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "expires",
            |m: &Proof| { &m.expires },
            |m: &mut Proof| { &mut m.expires },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "domain",
            |m: &Proof| { &m.domain },
            |m: &mut Proof| { &mut m.domain },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "challenge",
            |m: &Proof| { &m.challenge },
            |m: &mut Proof| { &mut m.challenge },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "proof_value",
            |m: &Proof| { &m.proof_value },
            |m: &mut Proof| { &mut m.proof_value },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::wrappers::StringValue>(
            "previous_proof",
            |m: &Proof| { &m.previous_proof },
            |m: &mut Proof| { &mut m.previous_proof },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::struct_::Value>(
            "nonce",
            |m: &Proof| { &m.nonce },
            |m: &mut Proof| { &mut m.nonce },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Proof>(
            "Proof",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Proof {
    const NAME: &'static str = "Proof";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.id)?;
                },
                18 => {
                    self.proof_type = is.read_string()?;
                },
                26 => {
                    self.proof_purpose = is.read_string()?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.verification_method)?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.cryptosuite)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.created)?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.expires)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.domain)?;
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.challenge)?;
                },
                82 => {
                    self.proof_value = is.read_string()?;
                },
                90 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.previous_proof)?;
                },
                98 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.nonce)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.id.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.proof_type.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.proof_type);
        }
        if !self.proof_purpose.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.proof_purpose);
        }
        if let Some(v) = self.verification_method.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.cryptosuite.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.created.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.expires.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.domain.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.challenge.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.proof_value.is_empty() {
            my_size += ::protobuf::rt::string_size(10, &self.proof_value);
        }
        if let Some(v) = self.previous_proof.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.nonce.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.id.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.proof_type.is_empty() {
            os.write_string(2, &self.proof_type)?;
        }
        if !self.proof_purpose.is_empty() {
            os.write_string(3, &self.proof_purpose)?;
        }
        if let Some(v) = self.verification_method.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.cryptosuite.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.created.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.expires.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.domain.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if let Some(v) = self.challenge.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        if !self.proof_value.is_empty() {
            os.write_string(10, &self.proof_value)?;
        }
        if let Some(v) = self.previous_proof.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(11, v, os)?;
        }
        if let Some(v) = self.nonce.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(12, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Proof {
        Proof::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.proof_type.clear();
        self.proof_purpose.clear();
        self.verification_method.clear();
        self.cryptosuite.clear();
        self.created.clear();
        self.expires.clear();
        self.domain.clear();
        self.challenge.clear();
        self.proof_value.clear();
        self.previous_proof.clear();
        self.nonce.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Proof {
        static instance: Proof = Proof {
            id: ::protobuf::MessageField::none(),
            proof_type: ::std::string::String::new(),
            proof_purpose: ::std::string::String::new(),
            verification_method: ::protobuf::MessageField::none(),
            cryptosuite: ::protobuf::MessageField::none(),
            created: ::protobuf::MessageField::none(),
            expires: ::protobuf::MessageField::none(),
            domain: ::protobuf::MessageField::none(),
            challenge: ::protobuf::MessageField::none(),
            proof_value: ::std::string::String::new(),
            previous_proof: ::protobuf::MessageField::none(),
            nonce: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Proof {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Proof").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Proof {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Proof {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x08vc.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobu\
    f/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xee\x04\n\x1cU\
    nsignedVerifiableCredential\x12\x19\n\x07context\x18\x01\x20\x03(\tR\x08\
    @context\x12,\n\x02id\x18\x02\x20\x01(\x0b2\x1c.google.protobuf.StringVa\
    lueR\x02id\x125\n\x0fcredential_type\x18\x03\x20\x01(\x0b2\x16.google.pr\
    otobuf.ValueR\x04type\x12*\n\x04name\x18\x04\x20\x01(\x0b2\x16.google.pr\
    otobuf.ValueR\x04name\x128\n\x0bdescription\x18\x05\x20\x01(\x0b2\x16.go\
    ogle.protobuf.ValueR\x0bdescription\x12.\n\x06issuer\x18\x06\x20\x01(\
    \x0b2\x16.google.protobuf.ValueR\x06issuer\x12E\n\x12credential_subject\
    \x18\x07\x20\x01(\x0b2\x16.google.protobuf.ValueR\x11credentialSubject\
    \x129\n\nvalid_from\x18\x08\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\
    \tvalidFrom\x12;\n\x0bvalid_until\x18\t\x20\x01(\x0b2\x1a.google.protobu\
    f.TimestampR\nvalidUntil\x124\n\x11credential_status\x18\n\x20\x01(\x0b2\
    \x07.StatusR\x10credentialStatus\x12C\n\x11credential_schema\x18\x0b\x20\
    \x01(\x0b2\x16.google.protobuf.ValueR\x10credentialSchema\"\x84\x05\n\
    \x14VerifiableCredential\x12\x19\n\x07context\x18\x01\x20\x03(\tR\x08@co\
    ntext\x12,\n\x02id\x18\x02\x20\x01(\x0b2\x1c.google.protobuf.StringValue\
    R\x02id\x125\n\x0fcredential_type\x18\x03\x20\x01(\x0b2\x16.google.proto\
    buf.ValueR\x04type\x12*\n\x04name\x18\x04\x20\x01(\x0b2\x16.google.proto\
    buf.ValueR\x04name\x128\n\x0bdescription\x18\x05\x20\x01(\x0b2\x16.googl\
    e.protobuf.ValueR\x0bdescription\x12.\n\x06issuer\x18\x06\x20\x01(\x0b2\
    \x16.google.protobuf.ValueR\x06issuer\x12E\n\x12credential_subject\x18\
    \x07\x20\x01(\x0b2\x16.google.protobuf.ValueR\x11credentialSubject\x129\
    \n\nvalid_from\x18\x08\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\tval\
    idFrom\x12;\n\x0bvalid_until\x18\t\x20\x01(\x0b2\x1a.google.protobuf.Tim\
    estampR\nvalidUntil\x124\n\x11credential_status\x18\n\x20\x01(\x0b2\x07.\
    StatusR\x10credentialStatus\x12C\n\x11credential_schema\x18\x0b\x20\x01(\
    \x0b2\x16.google.protobuf.ValueR\x10credentialSchema\x12\x1c\n\x05proof\
    \x18\x0c\x20\x01(\x0b2\x06.ProofR\x05proof\"\x97\x02\n\x16VerifiablePres\
    entation\x12\x19\n\x07context\x18\x01\x20\x03(\tR\x08@context\x12,\n\x02\
    id\x18\x02\x20\x01(\x0b2\x1c.google.protobuf.StringValueR\x02id\x127\n\
    \x11presentation_type\x18\x03\x20\x01(\x0b2\x16.google.protobuf.ValueR\
    \x04type\x12K\n\x15verifiable_credential\x18\x04\x20\x01(\x0b2\x16.googl\
    e.protobuf.ValueR\x14verifiableCredential\x12.\n\x06holder\x18\x05\x20\
    \x01(\x0b2\x16.google.protobuf.ValueR\x06holder\"i\n\x06Status\x12,\n\
    \x02id\x18\x01\x20\x01(\x0b2\x1c.google.protobuf.StringValueR\x02id\x121\
    \n\x0bstatus_type\x18\x02\x20\x01(\x0b2\x16.google.protobuf.ValueR\x04ty\
    pe\"=\n\x10CredentialSchema\x12\x0e\n\x02id\x18\x01\x20\x01(\tR\x02id\
    \x12\x19\n\x0bschema_type\x18\x02\x20\x01(\tR\x04type\"\xef\x04\n\x05Pro\
    of\x12,\n\x02id\x18\x01\x20\x01(\x0b2\x1c.google.protobuf.StringValueR\
    \x02id\x12\x18\n\nproof_type\x18\x02\x20\x01(\tR\x04type\x12#\n\rproof_p\
    urpose\x18\x03\x20\x01(\tR\x0cproofPurpose\x12M\n\x13verification_method\
    \x18\x04\x20\x01(\x0b2\x1c.google.protobuf.StringValueR\x12verificationM\
    ethod\x12>\n\x0bcryptosuite\x18\x05\x20\x01(\x0b2\x1c.google.protobuf.St\
    ringValueR\x0bcryptosuite\x124\n\x07created\x18\x06\x20\x01(\x0b2\x1a.go\
    ogle.protobuf.TimestampR\x07created\x124\n\x07expires\x18\x07\x20\x01(\
    \x0b2\x1a.google.protobuf.TimestampR\x07expires\x12.\n\x06domain\x18\x08\
    \x20\x01(\x0b2\x16.google.protobuf.ValueR\x06domain\x12:\n\tchallenge\
    \x18\t\x20\x01(\x0b2\x1c.google.protobuf.StringValueR\tchallenge\x12\x1f\
    \n\x0bproof_value\x18\n\x20\x01(\tR\nproofValue\x12C\n\x0eprevious_proof\
    \x18\x0b\x20\x01(\x0b2\x1c.google.protobuf.StringValueR\rpreviousProof\
    \x12,\n\x05nonce\x18\x0c\x20\x01(\x0b2\x16.google.protobuf.ValueR\x05non\
    ceb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(::protobuf::well_known_types::struct_::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::wrappers::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(6);
            messages.push(UnsignedVerifiableCredential::generated_message_descriptor_data());
            messages.push(VerifiableCredential::generated_message_descriptor_data());
            messages.push(VerifiablePresentation::generated_message_descriptor_data());
            messages.push(Status::generated_message_descriptor_data());
            messages.push(CredentialSchema::generated_message_descriptor_data());
            messages.push(Proof::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
