name: Deploy Rust Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger action on push to main branch (change if needed)
  pull_request:
    branches:
      - main  # Trigger action on pull requests to main

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build docs
      run: cargo doc --no-deps --all-features --release

    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./target/doc
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Optional: You can change the branch if you use a different branch
        publish_branch: gh-pages
